{% set name = "spots-in-yeasts" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spots-in-yeasts-{{ version }}.tar.gz
  sha256: 6f75a75d001917fb455e4e459a63594e47d377334b1948f97f541c84aaf6371b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - wheel
  run:
    - cellpose
    - magic-class
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - python >=3.8
    - qtpy
    - scikit-image
    - termcolor
    - tifffile

test:
  imports:
    - spots_in_yeasts
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/spots-in-yeasts/
  summary: A Napari plugin segmenting yeast cells and fluo spots to extract statistics.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MontpellierRessourcesImagerie/spots-in-yeasts

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
